//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECU_Debugger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECU_Debugger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CustomDebuggerCode {
            get {
                object obj = ResourceManager.GetObject("CustomDebuggerCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CustomDebuggerCode_VCAL {
            get {
                object obj = ResourceManager.GetObject("CustomDebuggerCode_VCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;##################################################################################
        ///;#############    ECU Debugger ROM Code                               #############
        ///;#############                                                        #############
        ///;#############    Uncomment the setup section for the target ECU      #############
        ///;#############    Uncomment the target patch section as well          #############
        ///;#############    use asm662 to compile this file                     #############
        ///;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debugger_ROM_Code {
            get {
                return ResourceManager.GetString("Debugger_ROM_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;##################################################################################
        ///;#############    ECU Debugger ROM Code                               #############
        ///;#############                                                        #############
        ///;#############    Uncomment the setup section for the target ECU      #############
        ///;#############    Uncomment the target patch section as well          #############
        ///;#############    use asm662 to compile this file                     #############
        ///;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debugger_ROM_Code_VCAL {
            get {
                return ResourceManager.GetString("Debugger_ROM_Code_VCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HTSDebuggerCode {
            get {
                object obj = ResourceManager.GetObject("HTSDebuggerCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HTSDebuggerCode_VCAL {
            get {
                object obj = ResourceManager.GetObject("HTSDebuggerCode_VCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P13DebuggerCode {
            get {
                object obj = ResourceManager.GetObject("P13DebuggerCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P13DebuggerCode_VCAL {
            get {
                object obj = ResourceManager.GetObject("P13DebuggerCode_VCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P13HTSDebuggerCode {
            get {
                object obj = ResourceManager.GetObject("P13HTSDebuggerCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P13HTSDebuggerCode_VCAL {
            get {
                object obj = ResourceManager.GetObject("P13HTSDebuggerCode_VCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P30DebuggerCode {
            get {
                object obj = ResourceManager.GetObject("P30DebuggerCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P30DebuggerCode_VCAL {
            get {
                object obj = ResourceManager.GetObject("P30DebuggerCode_VCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P72DebuggerCode {
            get {
                object obj = ResourceManager.GetObject("P72DebuggerCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P72DebuggerCode_VCAL {
            get {
                object obj = ResourceManager.GetObject("P72DebuggerCode_VCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
